import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import EmptyNavbar from "@/components/empty_navbar";
import "../globals.css";

export const metadata = {
  title: "onboarding",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Toaster richColors position="top-right" closeButton />
        <body>
          <header>
            <EmptyNavbar />
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
